
# Executive Summary {#sec-exec .unnumbered}

```{r}
#| echo: false
#| purl: false
enc <- function(x) {
    paste0('<span class="encode">', x, '</span>')
}
dec <- function(x) {
    paste0('<span class="decode">', x, '</span>')
}
```

::: {.exec-summary}

* Creating a data visualisation involves an 
  `r enc("**encoding**")` of
  <span style="color: #1A6000">**data values**</span> 
  as <span style="color: #005A8F">**visual features**</span>.

  For example, numeric <span style="color: #1A6000">**counts**</span> 
  are `r enc("**encoded**")` 
  as the <span style="color: #005A8F">**heights of bars**</span>
  to create a bar plot.

* Reading a data visualisation involves a 
  `r dec("**decoding**")` of
  <span style="color: #005A8F">**visual features**</span> 
  to obtain <span style="color: #1A6000">**data values**</span>.

  For example, the <span style="color: #005A8F">**heights**</span> of bars
  in a bar plot
  are `r dec("**decoded**")` 
  to obtain <span style="color: #1A6000">**counts**</span>.

* The <span style="color: #8D324A">**effectiveness**</span> 
  of a data visualisation depends on the
  effectiveness of the `r dec("**decoding**")`.

  For example, a bar plot is effective for comparing 
  <span style="color: #1A6000">**counts**</span>
  because the visual system is effective at comparing the 
  <span style="color: #005A8F">**heights**</span> of bars.

* More `r enc("**complex encodings**")` produce more 
  <span style="color: #005A8F">**complex visual features**</span>.

  For example, a scatter plot `r enc("**encodes**")`
  <span style="color: #1A6000">**two numeric variables**</span>
  as the x- and y-locations of points, 
  which produces the 
  <span style="color: #005A8F">**position in space**</span> of points.

* More <span style="color: #005A8F">**complex visual features**</span> 
  lead to more `r dec("**complex decodings**")`.

  For example, the 
  <span style="color: #005A8F">**position in space**</span> of points
  in a scatter plot
  is `r dec("**decoded**")` 
  as the <span style="color: #1A6000">**correlation**</span> 
  between two numeric variables.
  
* An <span style="color: #8D324A">**effective data visualisation**</span>
  <span class="encode">**encodes**</span> data values to
  visual features that facilitate an effective 
  <span class="decode">**decoding**</span> from visual features
  back to information about the data.

:::

