---
title: How Data Visualisation Works
author: Paul Murrell
toc: true
number-sections: true
bibliography: how-data-vis-works.bib
format: 
  html:    
    css: style.css
---

```{r}
#| echo: false
#| message: false
library(dplyr)
library(knitr)
library(kableExtra)
library(reshape2)
library(ggplot2)
library(scales)
library(colorspace)
library(ggsci)
library(grid)
```

```{r}
#| echo: false
figbg <- "#F2F2F2"
highlight <- "#7D12BA" ## Match text code colour (more precise than "purple")
## Set default colour palettes
scale_colour_discrete <- function(...) {
    scale_colour_npg(...)
}
scale_fill_discrete <- function(...) {
    scale_fill_npg(...)
}
scale_fill_ordinal <- function(...) {
    scale_fill_brewer(palette="Purples", ...)
}
scale_fill_continuous <- function(...) {
    scale_fill_distiller(palette="Purples", ...)
}
## Set default line width
update_geom_defaults("line", list(linewidth=1))
## Set default theme
theme_set(theme_bw())
## Match the table odd row fill
theme_update(plot.background=element_rect(colour=NA, 
                                          fill=figbg),
             panel.background=element_blank(),
             panel.grid.minor=element_blank(),
             panel.grid.major=element_blank(),
             legend.background=element_blank())
```

```{r}
#| echo: false
source("youth-crime.R")
crimeAgeSimple <- subset(crimeAge, age %in% c("14", "15", "16"))
```

```{r}
#| echo: false
#| purl: false
knitr::opts_chunk$set(dev='svg', 
                      dev.args=list(bg=figbg),
                      fig.width=8, fig.height=4,
                      out.width="100%")
```

{{< include intro.qmd >}}

{{< include visual-model.qmd >}}

{{< include mapping-visual-features.qmd >}}

# TODO

* colour (hue, chroma, luminance)
* ordinal visual features (chroma and luminance)
* CVD
* distance effect
* visual illusions

* Things that do not change are not salient (e.g., the widths of bars in
  bar plot), BUT things that DO change are salient (so only do this to
  represent changes in the data).  This should be cited to something.

&nbsp;
