
::: {.actual-quote}

*Visualization is essentially a mapping process from computer representations
to perceptual representations, choosing encoding techniques to maximize human
understanding and communication.*[^definition]
:::

[^definition]:
    This quote is from an early web resource on data visualisation
    that was produced by the ACM SIGGRAPH Education Committee [@owen1999].


# Preface {.unnumbered}

This is a book about data visualisation.

Like many books, it scratches an author's itch.

This particular itch began a long time ago, when first introduced to the
works of Edward Tufte.
Books like *The Visual Display of Quantitative Information*
and *Envisioning Information*[^tufte]
inspired an interest in how to produce effective graphics, but
they were also frustrating.

[^tufte]:
    *The Visual Display of Quantitative Information* [@tufte1983visual]
    and *Envisioning Information* [@tufte1990envisioning] are just two 
    of a series of influential and visually attractive books
    that also includes *Visual Explanations* [@tufte1997visual]
    and *Beautiful Evidence* [@tufte2006beautiful].

Reading a Tufte book to get better at data visualisation 
is a bit like watching Roger Federer play to get better at tennis.
It is possible to glean fragments of insight into the master's skill and
technique, but
it is difficult to come away with a clear set of rules for
how to succeed on our own.

At the same time,
encountering the work of William S. Cleveland presented 
a different problem.[^cleveland]
Here were hard experimental results with clear implications
for effective data visualisations:  use length not area; 
use bars not pies.
But they only told us about a small subset of the types of data
visualisations 
that we could create and they only told us about 
a small subset of the types of questions that we could
answer with those data visualisations.

[^cleveland]:
    There were several studies by Cleveland, some in collaboration with
    Robert McGill, which were summarised and extended in two books:
    *The Elements of Graphing Data* [@cleveland1985elements] and 
    *Visualizing Data* [@cleveland1993visualizing].

In the intervening decades since those first encounters, a lot has happened.

Data visualisation is an area of research for psychologists, 
for computer scientists, for geographers,
and even for statisticians.
The literature is wide and deep and complex.

This has significantly reduced the size of the second problem.
We know a lot more about a wider range of data visualisation types
and data visualisation tasks.
Unfortunately, this has introduced a new problem.
There are comprehensive and detailed overviews of 
current knowledge,[^ware-munzner] but it is now difficult 
to consume and make sense of so much knowledge.

[^ware-munzner]:
    *Information Visualization: Perception for Design* [@ware2021information]
    reviews a very wide range of research that has relevance to
    data visualisation in one way or another and 
    *Visualization Analysis and Design* [@munzner2014visualization]
    provides a comprehensive and theoretical coverage of 
    the complete process of creating effective data visualisations.

At the same time, there are more
accessible and practical guides for creating
effective data visualisations.[^healey-wilke]
These eschew much of the gory detail in favour of
simple, applicable advice.
The problem here is that, without the underlying 
explanations, the guidelines can become just a long laundry list to
commit to memory.
It is useful to know that bars should always start at zero,
but is more satisfying to know why.

[^healey-wilke]:
    For example, *Creating More Effective Graphs* [@robbins2005creating],
    *Data Visualization: A Practical Introduction* [@healy2018data],
    and *Fundamentals of Data Visualization: 
    A Primer on Making Informative and Compelling Figures* 
    [@wilke2019fundamentals].

For some of us there is a need for a middle path.
We would like to understand why we are making
certain data visualisation choices, but we have brains that can only
hold so many ideas at once.
For us there is utility in a framework
that contains a small number of core concepts,
that covers a wide range of data visualisations,
but connects them all with a relatively simple explanation.

This book attempts to provide such a framework.
It is a synthesis of a large number of research articles and books
and it is a simplification of a large amount of knowledge.
It is an attempt to prune the complexity so that we can see the 
forest through the trees, while at the same time leaving enough foliage that
we can still recognise a tree when we see one.

I hope that it helps.

## How to Read this Book

Although the goal is to provide a relatively simple conceptual
framework for thinking about data visualisation,
this is not a short book.
The [Executive Summary](exec.html) provides the simplest possible statement
of the framework and it may be useful to resurface and revisit this summary
if you become lost in the depths of one of the chapters.

A slightly longer summary of the framework is provided in 
the [Review](review.html). The Review also provides some guidance on 
how the framework can be applied to the creation of a new
data visualisation and the criticism of existing an one.

Another major issue with a subject this complex and a subject that
is studied from so many different angles is *terminology*.
There is no consistency across all of the different sources of
information from which this book was drawn, so all that we can do
is attempt to be consistent with ourselves.  Some of the most
important terms that will be reused relentlessly throughout this
book are highlighted in the [Executive Summary](exec.html).
The meaning of these terms is hopefully approximately what you 
already think, but they will be made clearer as the book progresses.

All section and figure cross-references are hyperlinks, so clicking
them will navigate to the relevant section or figure.
Even more helpfully, 
hovering the mouse over a hyperlink will
show a preview of the relevant section or figure.
This is particularly effective for figures because it obviates
the need to reproduce the same image multiple times;
just hover over the figure link to see the image that the text
is referring to.

## Acknowledgements

This book is based upon a large number of research articles and books,
but in order to make the text appear more accessible and friendly,
there are no formal citations in the main text.
There are, however, a large number of footnotes,
which provide the links between what is being described in the 
main text and the underlying research, and 
those footnotes contain proper citations.
The real work is not being ignored, it is just being hidden from view.

This book has been generated using the 
[Quarto publishing system](https://quarto.org/).
If any parts of the book look nice to you it is probably 
thanks to Quarto.

---

```{=latex}
\theendnotes
```
