
# Position {#sec-position}

Position is fundamental to our perception of an image.[^position-primary]

**NOTE** that this is going to have to stick to simple
demonstrations using bar plots (e.g., stacked vs dodged).
Don't get scatter plots until chapter 10 (!)
Case study q-q plots in combine.Rmd.
Ditto log-log plot.

[^position-primary]:
    "Design for Information : An Introduction to the Histories, Theories, 
    and Best Practices Behind Effective Information Visualizations"
    Isabel Meirelles (2013)
    "We process spatial properties (position and size) separately from object 
    properties (such as shape, color, texture, etc).  Furthermore, position 
    in space and time has a dominant role in perceptual organization, 
    as well as in memory."
    Ware (2004, 2008), Card et al. (1999), MacEachren (2004), Kosslyn (1994).
        
    "How Maps Work - Representation, Visualization, and Design"
    MACEACHREN A. M. (1995)
    quotes Kubovy (1981) who 
    includes position as one of the "indispensable attributes"

    "UNDERSTANDING GRAPHS AND TABLES"
    Wainer (1992)
    quotes Arthur H. Robinson and Barbara Bartz Petchenik (1976) who said, 
    "There is fairly widespread philosophical agreement, which certainly accords
    with commonsense, that the spatial aspects of all existence are
    fundamental. Before an awareness of time, there is an awareness of relations
    in space." They conclude their book with the observation that "the concept
    of spatial relatedness ... is a quality without which it is difficult or
    impossible for the human mind to apprehend anything."

## Aligned versus unaligned {#sec-unaligned-pos}

Elaborate on the classic order to allow for aligned vs unaligned.
Not entirely sure how to demo this with actual plot, though
in quantitative (length) there is an abstract demo.

```{r}
#| echo: false
#| label: fig-unaligned-pos
#| fig-cap: It is easier to compare two positions on the left because they are **aligned**;  they share a common baseline.  The two positions on the right are harder to compare because they are **unaligned**.
grid.newpage()
pushViewport(viewport(x=0, width=.5, just="left"))
pushViewport(viewport(width=unit(.8, "snpc")))
grid.segments(.2, .2, .2, .4, gp=gpar(col="grey"))
grid.segments(.7, .2, .7, .4, gp=gpar(col="grey"))
grid.segments(.2, .6, .2, .8, gp=gpar(col="grey"))
grid.segments(.7, .6, .7, .8, gp=gpar(col="grey"))
grid.segments(.2, c(.3, .7), .7, c(.3, .7), gp=gpar(lty="dotted"))
grid.circle(c(.45, .55), c(.3, .7), r=unit(2, "mm"), gp=gpar(fill="black"))
popViewport(2)
pushViewport(viewport(x=.5, width=.5, just="left"))
pushViewport(viewport(x=.4, width=unit(.8, "snpc")))
grid.segments(.2, .2, .2, .4, gp=gpar(col="grey"))
grid.segments(.7, .2, .7, .4, gp=gpar(col="grey"))
grid.segments(.3, .6, .3, .8, gp=gpar(col="grey"))
grid.segments(.8, .6, .8, .8, gp=gpar(col="grey"))
grid.segments(c(.2, .3), c(.3, .7), c(.7, .8), c(.3, .7), gp=gpar(lty="dotted"))
grid.circle(c(.45, .65), c(.3, .7), r=unit(2, "mm"), gp=gpar(fill="black"))
popViewport(2)
```

## Overplotting

If a data value is mapped to a representation that is not
visible, decoding is going to be a challenge.

Bring jittering case study back here.
Add link from birthday cake example back to jittering.

## Non-linear scales

The effective decoding of position is dependent on 
a linear encoding.[^tufte-prop]

[^tufte-prop]:
    Tufte, E. R. (1983). The Visual Display of Quantitative Information. 
    (Tufte also emphasized a similar principle: "The representation of numbers
    should be directly proportional to the quantities represented.")

In a non-linear encoding, the same visual difference does not
decode to the same data difference.
That is going to be confusing![^log-scales]

[^log-scales]:
    Proportional Ink and Logarithmic Scales
    https://callingbullshit.org/tools/logarithmic_scales.html
    If you plot log values, then the ink is proportional,
    but the numbers are harder to interpret
    (in my terms, you can only map back to log values)

Revisit in qualitative.Rmd to point out that non-linear ordinal scales
are ok, e.g., jet colour scale

## Summary

