
```{r}
#| echo: false
#| message: false
source("common.R")
```

# Review {#sec-review .unnumbered}

Add review at the end that reinforces the threads like visual feature, 
visual shape, visual object and mappings

Possible encoding end points:

* visual feature
* visual summary
* emergent feature
* visual shape 
* visual object
* text

Possible decodings from encoding end points:

* qual/quant data value
* data summary
* higher level information/knowledge/wisdom

Do two versions (at least):

* Set of questions for when you already have a plot and want to understand why
  it works or not

* Another set for if you want to create a data vis

Basic questions:

* What are you asking the visual system to do?
* Is the visual system good at that task? 
* Are you asking the viewer to produce visual summaries
  when it would be easier to produce data summaries?

Present process by which a data vis can be broken down.
What data symbols are being used?  (simple or complex)
What mappings are being used? 
What do we want to decode? (data or summaries)
If mapping back to raw data, are the mappings accurate?
What can be mapped back to?
Are mappings congruent with data?

...

* Use heatmap as case study?

* do the side-by-side pie chart idea as an example of reasoning your
  way to a new visualisation.

* Move the discussion/revisit of tables from text section to here ?

* Another possible application of data vis knowledge:
  Analyse one of the weird boxplot variations that look a bit like a ziggurat?


List of questions to evaluate a data vis (maybe nest these a bit):

* What do you want the viewer to be able to decode?
* Do the mappings support that goal?

* What are the data variables
* What visual features are they mapped to
* What type of data
* Can the visual features represent the data
* Is there the capacity to represent all categories
* How accurate are the decodings
* Is there congruence or dissonance in the mapping
* Mapping data or data summary
* Do visual features interact
* Are there emergent features
* Is the data symbol a visual shape
* Is that appropriate
* A visual object
* Is that appropriate
* Learned mappings somehow (distinct from implicit mappings)

* Do all visual differences correspond to differences in the data?
* Are all differences in the data represented by visual differences? 

* Does each data value map to its own data symbol
  If not, individual data values may be difficult to decode 
* Do multiple data values map to a single data symbol
  If not, data summaries may be difficult to decode 


And so on ...

