
# TODO {.unnumbered}

+ CC BY-NC-SA licence

+ Add ref to Coren and Girgus "Seeing is Deceiving" book for
  difference between horizontal and vertical decoding of line length?

+ shrink lots of plots into .9x.9 viewport ?

  Also look at adding titles and tweaking axis titles everywhere
  (OR rely on figure captions instead of titles?)

+ check for "encode to" instead of "encode as"

+ add review at end of each section and/or preview to start of 
  each section to reinforce the building concepts.

+ Use the  technique of foreshadowing summaries (at the start of each chapter)
  By the end of this chapter we will see how encoding using visual features 
  is an effective way to visualize data
  Examples of things to foreshadow are questions that Julia has raised
  Like what are we wanting to decode?

+ Also acknowledge things that are being ignored
  You might notice that we are ignoring the fact that there are two encodings
  We will get to their interaction in chapter 5
  Might need to fill these in as students ask questions

+ accumulate summaries over chapters, so each summary includes 
  all previous summaries and then adds its own new summary.
  Use greyscale gradient to diminish previous summaries?

+ Keep all important points and chapter summaries 
  in terms of encoding and decoding

+ Rewrite visual model with much more emphasis on what you are able to decode
  Eg lots of simple info from visual features
  Worry less about giving the game away for later sections 

+ Add more back refs to @sec-visual-focus and @sec-memory 
  wherever the complexity/simplicity
  of a data visualisation is discussed (likely to already reference
  visual differences and/or visual similarities).

+ Check that every visual system topic is connected to a visual decoding topic.
  Possibly rename sections, e.g., "visual differences" -> "decoding differences"

+ Check that I have used "pattern" to refer to data point "shape" everywhere
  (both to avoid conflict with "visual shape" and to allow connection to
  early detection of "pattern" or "texture" or "spatial frequency" in 
  visual processing).

+ Is there a single data vis example that has a realistically
  large amount of data in it ?

  There are a couple in Visual Shapes

  Could add in an example or two in Multiple Mappings

+ Check Few (2004) quote!

+ Put more of Review in Exec Summary ?

+ Try pal_npg()(2)[1] as highlight colour ?

+ Flesh out all footnotes

+ Add alt text to ALL figures (fig-alt)

+ Check that colour palettes are ok for CVD

+ Look for "Total" data frames and replace with subset(year == 2021) data frames
  (in example data visualisations)

+ review https://friendly.github.io/6135/lectures/GraphPerception.pdf
  from https://friendly.github.io/6135/index.html
  (especially the stuff on basic models of visual perception
  and cognition!)
  to see that (i) I am covering everything and (ii) I am not
  telling too many lies.

+ Note that "correlations" do not have to be linear, e.g.,
  some of the pairwise scores in R Journal submission 2024-88 [p 3]
  are designed to pick up non-linear correlations (?)

+ Need to work in the idea that what is most is important is whether    
  the viewer can easily see what you want them to see.
  So, for example, it is ok to use less effective mappings like in
  a heatmap if you do not need to viewer to extract raw data values.
  Maybe this point needs to be made several times throughout the book.

* Early on when talk about how visual system is good at stuff and that is why
  data vis works

  Data vis is trading advantage of the visual system to immediately and
  effortlessly convey a message

  Flip the script and point out that if the viewer cannot immediately see what
  you want them to see then you are either doing it wrong or data vis is the
  wrong way to communicate the message

* When talk about basic data types and what you can do with them,
  maybe introduce the explicit idea of "comparison" and all tasks
  basically being based on comparison (with some examples of breaking
  down tasks).
  There is a nice simple list of tasks (rather than some overblown
  task taxonomy) in 
  "Low-Level Components of Analytic Activity in Information Visualization"
  Amar et al (2005)
  which describes comparison as a "fundamental cognitive action" that
  underlies all data vis tasks.

* Check whether HDVW covers all of the types of tasks in 
  "Low-Level Components of Analytic Activity in Information Visualization"
  Amar et al (2005)

* Add spine plot to congruence ?
  Proportions via bar plot

* In visual-model, make a BRIEF statement at the end of each section 
  (maybe in black box) about the implications for data vis. 
  BUT keep it in terms of encode/decode

* Add the purpose of each type of plot as they are introduced so that 
  explanation of effectiveness is relative to it's purpose
  Eg a bar plot is effective at... Because... 

* add plot of differences between lines in crimegroup line plot ?
  (do NOT perceive vertical difference)
  citation?  see franconeri 2021

* In Multiple Mappings, add an example of a numerical data summary
  that is encoded as basic visual features (e.g., MDS, PCA, ...).
  Compare encoding data summary as visual feature with
  encoding data as visual shape.
  Decoding more straightforward, but issues with interpreting
  data summaries?  

* check have not missed any major pros or cons for choropleth maps
  https://www.practicalreporting.com/blog/2024/8/21/ive-stopped-using-colored-region-choropleth-maps-should-you

  Should have section on maps (cartography) as well ?
  This is the source of a lot of the background information

* Change from qualitative and quantitative to categorical and continuous ?
  (to be consistent about avoiding technical terminology)

  Shift nominal, ordinal, etc to footnote

  Just add ordered data in colour

  This would be a BIG edit.

* attributions for data sources 
  AND for images (like robber image)

* citations to stuff on pictographs and glyphs and icon-based plots
  (in clutter section?)

* add citations for R packages used in plots and diagrams.
  General one for R and ggplot2, then specific ones for specific plots
  Add citation to {ggsci} for default (discrete) palette

  Maybe an appendix ?

  R package {wordcloud} [@pkg-wordcloud].
  ggsci for colour palettes?

  Include {gMOIP} and {geometry} for HCL diagrams.

  Package for wind figure (e.g., rNOMADS)

* Get visualisation of uncertainty in somewhere ?
  Variability is a data summary, which we map to a visual feature.
  Box plots already do this.
  Only opportunity to demonstrate gradients as a visual feature?

* Add section on "Mapping Unintentionally" or something that looks at
  the information that is conveyed by style (e.g., conservative/liberal,
  young/old) and the interaction between the viewer's pre-existing
  attitudes.

  Goes in text section?

* Add footnote in @sec-quant-features to acknowledge that there are
  many other types of data (time series, cyclic, data with a 
  central neutral value, ...).  We see some of these in later chapters.

* Use the Data Rocks advice to generate a colour palette for this document ?
  
  https://buttondown.com/datarocksnz/archive/design-matters-6-the-ultimate-dashboard-colour/

* An index that links to all of the places that different sorts of plots
  are discussed ?

  Use Quarto book format (each .qmd becomes its own chapter) and
  then get search functionality for free (which is essentially 
  an automated index).

  Can also follow instructions to "publish" on GitHub pages

* For 3d rgl plot, add contingency code so that, if webgl is not available
  it falls back to a static image (online).

  Consider generating animations of both 3d rgl with rglplus::rgl.makemovie()
  and rayshader plots with render_movie()

* Match plot font to text font ?
  Would need to set more explicit text font on web 
  (currently system-ui is top of the list)

* Add sub-figs for all two-column figures (and change
  links in text to point to a) and b) rather than "left" and "right"
  
* Check all references, especially the ones generated by chatgpt !

* add how-to-cite

* add version information

* add docker container to build in

* add exercises at end of reach chapter

  Build them up from 787 labs 
