# Generated by copilot

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import colour.colorimetry as colorimetry
from colour import (
    SpectralDistribution,
    sd_to_XYZ,
    XYZ_to_Luv,
    Luv_to_uv,
    SDS_ILLUMINANTS
)

# Setup
cmfs = colorimetry.MSDS_CMFS_STANDARD_OBSERVER['CIE 1931 2 Degree Standard Observer']
illuminant = SDS_ILLUMINANTS['D65']
wavelengths = np.arange(380, 781, 5)
L_values = np.arange(10, 101, 10)

# Storage
boundary_data = []

# Loop over wavelengths to get spectral locus
for wl in wavelengths:
    reflectance = {w: 0.0 for w in wavelengths}
    reflectance[wl] = 1.0  # monochromatic reflectance
    sd = SpectralDistribution(reflectance)
    sd.align(cmfs.shape)

    XYZ = sd_to_XYZ(sd, cmfs, illuminant)

    for L in L_values:
        Luv = XYZ_to_Luv(XYZ, illuminant)
        Luv[0] = L  # override lightness
        uv = Luv_to_uv(Luv)
        boundary_data.append({'L': L, 'u': uv[1], 'v': uv[2], 'wavelength': wl})

# Convert to DataFrame
df = pd.DataFrame(boundary_data)

df.to_csv("cie_luv_spectral_boundary_copilot.csv", index=False)
